import { ArrowRight, Lock } from 'lucide-react';
import { ReignovaIcon } from '@/components/brand/ReignovaLogo';
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';

export default function HomePage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-6 text-center">
      <Card className="w-full max-w-md reignova-card border-border/60 shadow-2xl relative overflow-hidden">
        {/* Glow circle */}
        <div className="absolute -top-16 -right-16 size-32 bg-primary/20 rounded-full blur-2xl pointer-events-none" />

        <CardHeader className="flex flex-col items-center gap-4 text-center">
          {/* Logo and Icon */}
          <div className="inline-flex justify-center shadow-lg rounded-2xl">
            <ReignovaIcon size={64} className="size-16 rounded-2xl" />
          </div>

          <div className="flex flex-col gap-1.5">
            <CardTitle className="text-2xl font-bold tracking-tight text-white">
              Reignova Checkout
            </CardTitle>
            <CardDescription className="text-sm text-muted-foreground leading-relaxed">
              High-performance, secure mobile money checkout orchestration for modern African commerce.
            </CardDescription>
          </div>
        </CardHeader>

        <CardContent className="flex flex-col gap-4">
          <div className="reignova-card-inner rounded-xl p-4 text-left border border-border/40 flex flex-col gap-2">
            <div className="flex items-center gap-2">
              <Badge variant="outline" className="border-primary/30 text-primary bg-primary/10 gap-1 font-mono text-xs">
                <Lock className="size-3 text-primary" />
                <span>Hosted Checkout Session</span>
              </Badge>
            </div>
            <p className="text-xs text-muted-foreground leading-relaxed">
              To make a payment, please use the unique checkout link generated by your merchant or platform.
            </p>
          </div>
        </CardContent>

        <CardFooter className="flex justify-center border-t border-border/40 pt-4">
          <Button
            asChild
            variant="ghost"
            size="sm"
            className="text-xs font-semibold text-primary hover:text-primary hover:bg-primary/10 gap-1.5"
          >
            <a
              href="https://reignovatechnologies.com"
              target="_blank"
              rel="noopener noreferrer"
            >
              <span>Visit Reignova Technologies</span>
              <ArrowRight data-icon="inline-end" />
            </a>
          </Button>
        </CardFooter>
      </Card>
    </main>
  );
}
