import Link from 'next/link';
import { ShieldCheck, ArrowRight, Lock } from 'lucide-react';

export default function HomePage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-6 text-center">
      <div className="w-full max-w-md reignova-card rounded-2xl p-8 border border-white/10 shadow-2xl relative overflow-hidden">
        {/* Glow circle */}
        <div className="absolute -top-16 -right-16 w-32 h-32 bg-brand-accent/20 rounded-full blur-2xl pointer-events-none" />
        
        {/* Logo and Icon */}
        <div className="mx-auto mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-brand-navy-900 border border-brand-accent/30 text-brand-accent glow-accent-subtle">
          <ShieldCheck className="h-8 w-8" />
        </div>

        <h1 className="text-2xl font-bold tracking-tight text-white mb-2">
          Reignova Checkout
        </h1>
        <p className="text-sm text-brand-slate-400 mb-6 leading-relaxed">
          High-performance, secure mobile money checkout orchestration for modern African commerce.
        </p>

        <div className="reignova-card-inner rounded-xl p-4 text-xs text-brand-slate-400 text-left space-y-2 mb-6 border border-white/5 font-mono">
          <div className="flex items-center gap-2 text-brand-cream-100">
            <Lock className="w-3.5 h-3.5 text-brand-accent" />
            <span>Hosted Checkout Session</span>
          </div>
          <p className="text-xs text-brand-slate-400 font-sans">
            To make a payment, please use the unique checkout link generated by your merchant or platform.
          </p>
        </div>

        <a
          href="https://reignovatechnologies.com"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-2 text-xs font-semibold text-brand-accent hover:text-brand-accent-hover transition-colors"
        >
          <span>Visit Reignova Technologies</span>
          <ArrowRight className="w-3.5 h-3.5" />
        </a>
      </div>
    </main>
  );
}
